### ISSUE TITLE
Big Liquor data loading

### ISSUE THREAD

**Issue by parambidja** [Transformity/pos-db#17]

**Comment by parambidja** [comment]
install target: tuesday march 5th

**Comment by parambidja** [comment]
I will have the data by tomorrow

**Comment by jay-babu** [comment]
Manual Steps:

- Kegs will have to be manually set for bottle deposits

**Comment by parambidja** [comment]
All referenced IDs are item IDs:

- Need to delete unnecessary deposit items:
![Image](https://github.com/Transformity/pos-db/assets/19823906/2e46bee9-66b5-426e-ae88-0ddb04e3912a)

- I see many items which seem to have incorrect bottle deposit multipliers. Examples with 6PK but different multiplier: 639236, 637763, 637835, 638575

- Same for wrong env fees: 638040, 638014

- Seeing lots of Misc department items, which belong in other departments. Ex. 638057, 639407

- There are 172 items named "NEW ITEM". Their existing DB has this?

- No items have barcode 3 and 4. Just want to confirm that's validated in their existing DB.

- Looks like many popular items don't have a last cost (ex. 637739), can you confirm that's missing from their old DB? If so, let's set the last cost to 30% below the sell price. I ran a query to find 30% is their average markup

**Comment by parambidja** [comment]
- There aren't any historical bottle deposits and env fees paid it seems

**Comment by jay-babu** [comment]
> I see many items which seem to have incorrect bottle deposit multipliers. Examples with 6PK but different multiplier: 639236, 637763, 637835, 638575

![Image](https://github.com/Transformity/pos-db/assets/36803168/575054f7-c989-45d1-98eb-5e242e48c7ff)

![Image](https://github.com/Transformity/pos-db/assets/36803168/6f83ac9b-68f3-45b0-b8ee-8742006b558c)

This is from his system. it is setup that way

> Same for wrong env fees: 638040, 638014

Discussed this. he just adds it to their price and cost and doesn't want to change anything

> Seeing lots of Misc department items, which belong in other departments. Ex. 638057, 639407

Discussed this a lot of his items are wrong

> There are 172 items named "NEW ITEM". Their existing DB has this?

Discussed, these are samples he gets that he sells and never gets again. nothing to do

> No items have barcode 3 and 4. Just want to confirm that's validated in their existing DB.

yes, he doesn't use multiple barcodes. he just creates new items

> Looks like many popular items don't have a last cost (ex. 637739), can you confirm that's missing from their old DB? If so, let's set the last cost to 30% below the sell price. I ran a query to find 30% is their average markup

![Image](https://github.com/Transformity/pos-db/assets/36803168/ab6a979f-dc82-4a90-80b0-52209709f101)

The item you mentioned doesn't have a cost. There are ~1400 items in his database that don't have a cost. we should ask if we should do the 30% below or if he just wants a list of the items and he wants to update them

**Comment by jay-babu** [comment]
> There aren't any historical bottle deposits and env fees paid it seems

correct. trying to do this would get very complicated as it involves heavily modifying the transaction. doesn't seem worth doing
